name: Setup Node/NPM
description: Standard node/npm setup & dependency install
inputs:
  dependencies:
    required: false
    description: install dependencies?
    default: "true"
runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Install Dependencies
      uses: bahmutov/npm-install@v1.8.9
      if: inputs.dependencies == 'true'
      with:
        useRollingCache: true
        install-command: npm ci --prefer-offline --force
