name: Gitflow Continuous Integration

on:
  push:
    branches:
      - develop
jobs:
  cancel:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
  js-test:
    name: Javascript Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Node
        uses: ./.github/actions/setup-node
      - name: Test
        run: npm run test
  chromatic-deployment:
    name: Storybook Visual Regression Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Prepare Node
        uses: ./.github/actions/setup-node
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}